### ISSUE TITLE
NEON AG sites are running with generic crop rather than prognostic crop

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/CTSM#1889]
### Brief summary of bug

NEON crop sites such as SJER run with generic crop rather than prognostic crop.

### General bug information

**CTSM version you are using:** ctsm5.1.dev113

**Does this bug cause significantly incorrect results in the model's science?** Yes?

**Configurations affected:** NEON agriculture sites

### Details of bug

Both run_neon and compsets such as I1PtClm51Bgc and IHist1PtClm51Bgc run with prognostic crop off. This is fine for most NEON sites as it doesn't matter, since they don't have any crop vegetation. But, the agriculture sites probably should run with prognostic crop on. So they need to use a different compset, or need to explicitly turn crop on.

### Important details of your setup / configuration so we can reproduce the bug

./run_neon.py --setup-only --overwrite --neon-site SJER --run-type ad

### Important output or errors that show the problem

It runs without error, but use_crop is off, which means that it will be using generic crop in place of prognostic crop types.

**Comment by ekluzek** [comment]
It looks like the NEON sites that should run with prognostic crop are:

> SJER  =  17
> SOAP  =  17
> TEAK  =  17
> TOOL  =  17
> BARR  =  18
> BONA  =  19
> DEJU  =  19
> HEAL  =  19
> PUUM  =  20

**Comment by ekluzek** [comment]
Looks like the SJER surface dataset is pointing to the wrong PFT type. It's pointing to c3_non-arctic_grass, but should be pointing to temperate_crop. So it's not even running with a generic crop.

**Comment by negin513** [comment]
Hello @ekluzek. Not sure about the new datasets created recently. But for the older surface datasets, first I used `--crop` in subset_data and then I additionally put in some checks for AG sites specifically :

https://github.com/ESCOMP/CTSM/blob/fbfa05f19a645a4921997814e0e7c58a9317d307/tools/site_and_regional/modify_singlept_site_neon.py#L669-L687


At the time these were the only AG sites we had data for. So maybe we should add the other AG sites here.

**Comment by negin513** [comment]
Here is the issue about KONA and STER: #1606 was fixed in https://github.com/ESCOMP/CTSM/pull/1461
Also #1871 points to similar thing.

**Comment by ekluzek** [comment]
Ahh, @negin513 thanks for that! I was reading the wrong column of neon_sites_dompft.csv! Looks like the AG sites are still just KONA and STER. It does look like the latest datasets are still not right for those two though. It looks like it was run through modify_singlept_site_neon.py by @wwieder though, so I'm not sure what's up there.

**Comment by ekluzek** [comment]
Ahh, wait -- no the surface datasets are correct! Sorry. The general issue of not running prognostic crop for these two is still there though. But, the surface datasets are correct.

**Comment by wwieder** [comment]
Looks like you have this straightened out correctly in the updated file @ekluzek .  @negin513 thanks for clarifying this quickly.
